version: '3.8'

services:
  web:
    build: .
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./media:/app/media
      - ./static:/app/static
    env_file:
      - .env
    depends_on:
      - db
    command: >
      pwsh -Command "
        python manage.py migrate;
        if ($LASTEXITCODE -eq 0) {
          gunicorn --bind 0.0.0.0:8000 call_analyzer.wsgi:application
        }
      "

  db:
    image: postgres:14
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"

volumes:
  postgres_data:
