services:
  # Backend API Service
  - type: web
    name: ai-call-analyzer-backend
    env: python
    region: singapore  # Choose a region close to your users
    buildCommand: pwsh -Command "pip install -r requirements.txt; if ($LASTEXITCODE -eq 0) { python manage.py collectstatic --noinput; if ($LASTEXITCODE -eq 0) { python manage.py migrate } }"
    startCommand: gunicorn call_analyzer.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ASSEMBLY_AI_API_KEY
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: ai-call-analyzer-db
          property: connectionString
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: FRONTEND_URL
        value: "https://ai-call-analyzer-frontend.onrender.com"
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: DJANGO_SETTINGS_MODULE
        value: "call_analyzer.settings"

  # Frontend Service
  - type: web
    name: ai-call-analyzer-frontend
    env: node
    region: singapore  # Choose a region close to your users
    buildCommand: pwsh -Command "cd frontend; if ($LASTEXITCODE -eq 0) { npm install; if ($LASTEXITCODE -eq 0) { npm run build } }"
    startCommand: pwsh -Command "cd frontend; if ($LASTEXITCODE -eq 0) { NODE_ENV=production node server.js }"
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: "https://ai-call-analyzer-backend.onrender.com"
      - key: NODE_ENV
        value: "production"
      - key: PORT
        value: "3000"

# Database
databases:
  - name: ai-call-analyzer-db
    plan: free
    region: singapore  # Choose a region close to your users
